services:
  productorderapi:
    image: ${DOCKER_REGISTRY-}productorderapi
    build:
      context: ProductOrderApi
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=Server=db;Port=3306;Database=productorderdb;User=admin;Password=adminpassword;
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: productorderdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpassword
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: